name: jiosaavn
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  retrofit: ^4.9.0
  json_annotation: ^4.9.0
  logger: ^2.6.2
  freezed_annotation: ^3.1.0
  dio: ^5.9.0
  # path: ^1.9.0

dev_dependencies:
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  lints: ^5.0.0
  retrofit_generator: ^10.1.4
  test: ^1.25.6
